version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    volumes:
      - ./src/:/app
      - ./log/php:/var/log/php
    environment:
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT1:-80}:80
      - ${WEB_PORT2:-443}:80
    depends_on:
      - app
    volumes:
      - ./src/:/app