version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/laravel/Dockerfile
    volumes:
      - ./src/:/app
      - ./log/php:/var/log/php

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - ${WEB_PORT1:-80}:80
      - ${WEB_PORT2:-443}:80
    depends_on:
      - app
    volumes:
      - ./src/:/app